; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter = +<uno/> -<esp_controller/> -<esp_reciever/>

[env:esp_controller]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    gmag11/QuickEspNow @ 0.8.1
build_src_filter = +<esp_controller/> -<uno/> -<esp_reciever/>
build_flags = -D CONTROLLER -I include

[env:esp_reciever]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    gmag11/QuickEspNow @ 0.8.1
build_src_filter = +<esp_reciever/> -<uno/> -<esp_controller/>
build_flags = -D RECIEVER -I include

[env:esp_robot]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    gmag11/QuickEspNow @ 0.8.1
    robtillaart/AS5600
    dfrobot/DFRobot_BMI160
    arduino-libraries/Madgwick
build_src_filter = +<esp_robot> -<esp_reciever/> -<uno/> -<esp_controller/>
build_flags = -D ROBOT -O3 -ffast-math -I lib_comp

[env:esp_ros]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
build_src_filter = +<esp_ros> -<esp_robot/> -<esp_reciever/> -<uno/> -<esp_controller/> -<sensor_test/>
build_flags = -D ESP_ROS -O3 -ffast-math -I lib_comp

[env:sensor_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    dfrobot/DFRobot_BMI160
    https://github.com/adafruit/Adafruit_VL53L0X
build_src_filter = +<sensor_test> -<esp_robot/> -<esp_reciever/> -<uno/> -<esp_controller/>
build_flags = -D SENSOR_TEST

[env:esp_comp]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    gmag11/QuickEspNow @ 0.8.1
    robtillaart/AS5600
    dfrobot/DFRobot_BMI160
    arduino-libraries/Madgwick
    https://github.com/adafruit/Adafruit_VL53L0X
build_src_filter = +<esp_comp> -<esp_robot/> -<esp_reciever/> -<uno/> -<esp_controller/> -<sensor_test/>
build_flags = -D COMPETITION -O3 -ffast-math -I lib_comp

[env:esp_hardcode]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/adafruit/Adafruit_VL53L0X
build_src_filter = +<esp_hardcode/> -<esp_comp/> -<esp_robot/> -<esp_reciever/> -<uno/> -<esp_controller/> -<sensor_test/> -<esp_ros/>
build_flags = -D HARDCODE -O3 -ffast-math -I lib_comp